### ISSUE TITLE
Deleting entities without invalidating the iterator and data.

### ISSUE THREAD

**Issue by nassorc** [chrischristakis/seecs#2]
Hello, I've implemented a solution that could possibly allow the safe deletion of entities while using the `.ForEach` method.

Deleting an entity while iterating with a loop or the `.ForEach` could be error prone, since the code is swapping the deleted entity with the last element and the loop will eventually attempt to access this last element. So, the suggested approach is to mark them down during the loop and then deal with the deleted entities after.

If the order of the data isn't important, then looping through the data in reverse could remove the extra step needed for deletion. Deletion can be done without causing an error since we guarantee the deleted entity is swapped with an entity we've already processed and the loop won't run into the issue of processing entities that no longer exists.

So instead of the suggested approach:
```c++
vector<EntityID> marked;
ecs.ForEach<HealthComponent>([&ecs, &marked](EntityID id, HealthComponent& hc) {
    if(hc.health <= 0)
      marked.push_back(id);
});

// Safely delete after iteration!
for (EntityID id : marked)
  ecs.DeleteEntity(id);
```
we could have this instead:
```c++
ecs.ForEach<HealthComponent>([&ecs](seecs::EntityID id, HealthComponent& hc) {
    ecs.DeleteEntity(id);
});
```

This approach could also be used with Views.

Would you be open for a PR implementing this?

**Comment by chrischristakis** [comment]
Sure! Would be happy to take a look and merge if it works out :)

**Comment by chrischristakis** [comment]
(Copied from PR)
I like the idea!! Going backwards through an entity list is smart, since that allows us to swap-and-delete without ruining the iteration order.

The question I have though is that groups.push_back(ids); should be creating a deep copy of the SparseSet, and std::vector<EntityID> data = itr->Data(); also creates a deep copy of the dense data as well.

So to test, I tried changing your code to this:

// Forward iteration
for (auto itr = groups.begin(); itr != groups.end(); itr++) {
   std::vector<EntityID> data = itr->Data();

   for (int i = 0; i < data.size(); i++) {
      //...
   }
}

And it still works! (Because we're modifying the original list when we call ecs.DeleteEntity(id);, while iterating a copy)

Although I think it's possible to do this in place without having to make a copy of the groups if we iterate the groups + dense list backwards like you've pointed out, This only will work if all we're doing is deleting entities in a ForEach loop. In the case where we add/remove components, like:

ecs.ForEach<Position>([&ecs](seecs::EntityID id, Position& pos) {
        ecs.Add<Velocity>(id); // Add velocity component, change the group that 'id' belongs to (Or make a new one)
});

This will change what group an entity belongs to, and we can't really predict whether the group the current entity is added to comes before or after the current group we're iterating, resulting in us (potentially) iterating the same entity twice if it gets added to a group that comes after the current one; Hence why I think iterating on a copy while modifying the original is a safer approach (Which is what your code is doing anyway).

Sorry for the yap, just wanted to explain it and get your thoughts, will merge it in shortly
